insert into city values(1,'Salzburg',null);
insert into city values(2,'Singapore',null);
insert into city values(3,'Capetown',null);
insert into city values(4,'New York',null);
insert into city values(5,'Beijing',null);
insert into city values(6,'Zurich',null);
insert into city values(7,'Gold Coast',null);
insert into city values(8,'Honolulu',null);
insert into city values(9,'Buenos Aires',null);
insert into city values(10,'London',null);